services:
  postgres:
      image: "postgres"
      environment:
        POSTGRES_DB: yata-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mysecretpassword
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d yata-db"]
        interval : 5s
        timeout: 5s
        retries: 3

volumes:
  postgres_data: